[workspace]
authors = ["Qwacktuz <104035252+Qwacktuz@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gamejam26"
platforms = ["osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = ">=2.4.2,<3"

[pypi-dependencies]
pygame-ce = ">=2.5.6, <3"
